import { LineEdit, Button, ProgressIndicator, HorizontalBox, GroupBox } from "std-widgets.slint";

export struct LogItem {
    title: string,
}
export component AppWindow inherits Window {
  title: "m3u8downloader v0.1.0";

  in-out property <bool> enable-start-btn: true;
  in-out property <bool> enable-pause-btn: false;
  in-out property <bool> enable-cancel-btn: false;
  in-out property <bool> is-pause: false;
  in-out property <string> work-dir;
  in-out property <string> message;
  in-out property <string> total;
  in-out property <float> percent;
  in-out property <int> progress;
 
  out property <string> video-dir;
  out property <string> m3u8-url;
  out property <string> threads: 4;
  out property <string> retry: 3;
  out property <string> timeout: 5;

  callback select-dir();
  callback start-download();
  callback pause-download();
  callback cancel-download();

  VerticalLayout {
    width: root.width;
    padding: 8px;
    spacing: 4px;

    GridLayout {
      spacing: 6px;
      Row {
        Rectangle {
          width: 110px;
          Text {
            text: "Working Directory";
          }
          Text {
            x: 105px;
            text: "*";
            color: red;
          }
        }
        LineEdit {
          text <=> root.work-dir;
          read-only: true;
        }
        Button {
          enabled: !root.is-pause;
          text: "Change";
          clicked => { root.select-dir(); }
        }
      }

      Row {
        Rectangle {
          Text {
            text: "M3U8 URL";
          }
          Text {
            x: 86px;
            text: "*";
            color: red;
          }
        }
        LineEdit {
          text <=> root.m3u8-url;
          colspan: 2;
          enabled: !root.is-pause;
        }
      }

      Row {
        Rectangle {
          Text {
            text: "Video Name";
          }
          Text {
            x: 92px;
            text: "*";
            color: red;
          }
        }
        LineEdit {
          text <=> root.video-dir;
          colspan: 2;
          enabled: !root.is-pause;
        }
      }

      Row {
        Rectangle {
          Text {
            text: "Threads";
          }
        }
        LineEdit {
          text <=> root.threads;
          input-type: number;
          colspan: 2;
        }
      }

      Row {
        Rectangle {
          Text {
            text: "Retry";
          }
        }
        LineEdit {
          text <=> root.retry;
          input-type: number;
          colspan: 2;
        }
      }

      Row {
        Rectangle {
          Text {
            text: "Timeout(s)";
          }
        }
        LineEdit {
          text <=> root.timeout;
          input-type: number;
          colspan: 2;
        }
      }
    }

    VerticalLayout {
      HorizontalBox {
        x: parent.width - 265px;
        Button {
          width: 80px;
          text: root.is-pause ? "Continue" : "Download";
          enabled: root.enable-start-btn && !root.work-dir.is-empty && !root.video-dir.is-empty && !root.m3u8-url.is-empty;
          primary: true;
          clicked => {
            root.enable-start-btn = false;
            root.start-download();
          }
        }
        Button {
          width: 80px;
          text: "Pause";
          enabled: root.enable-pause-btn;
          clicked => {
            root.enable-pause-btn = false;
            root.pause-download();
          }
        }
        Button {
          width: 80px;
          text: "Cancel";
          enabled: root.enable-cancel-btn;
          clicked => {
            root.enable-cancel-btn = false;
            root.cancel-download();
          }
        }
      }
      HorizontalBox {
        Text {
          text: "Progress " + (!root.total.is-empty ? root.progress : "") + root.total;
        }
      }
      HorizontalBox {
        ProgressIndicator {
          progress: root.percent;
        }
      }
      Text {
        text: root.message;
        wrap: word-wrap;
        horizontal-alignment: center;
      }
    }
  }
}