import {
    TabWidget,
    LineEdit,
    Button,
    VerticalBox,
    HorizontalBox,
    CheckBox,
    Palette
} from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "M3U8Downloader";
    width: 350px;
    height: 470px;
    
    // 按钮组
    in-out property <bool> enable-start-btn: true;
    in-out property <bool> enable-pause-btn: false;
    in-out property <bool> enable-cancel-btn: false;

    // 状态组
    in-out property <bool> is-downloading: false;
    in-out property <bool> is-pause: false;
    in-out property <bool> has-failed-file: false;
    in-out property <bool> is-merge: false;
    in-out property <bool> is-delete-segment: false;

    // 输入组（后端可读可写）
    // in-out property <string> work-dir;
    in-out property <string> work-dir: "F:\\temp";
    in-out property <int> total_nums;
    in-out property <int> downloaded_nums;
    in-out property <string> content-length;

    // 输入组（后端只读）
    // out property <string> m3u8-url;
    out property <string> m3u8-url: "http://localhost/res/videos/m3u8/8/index.m3u8";
    // out property <string> video-name;
    out property <string> video-name: "m3u8test";
    out property <string> threads;
    out property <string> retry;
    out property <string> timeout;
    out property <string> message;
    out property <bool> is-err-msg;
    out property <color> normal-msg-color: Palette.color-scheme == ColorScheme.light ? #323130 : #e6e6e6;

    out property <string> github: "https://github.com/ljxh2024/m3u8downloader";

    // 回调函数
    callback select-dir();
    callback open-failed-file();
    callback start-download();
    callback pause-download();
    callback cancel-download();

    callback show-message(string, bool);
    show-message(msg, err) => {
        root.message = msg;
        root.is-err-msg = err;
    }

    // 总布局
    TabWidget {
        // 首页
        Tab {
            title: "主页";
            VerticalBox {
                // 输入组件，3列
                GridLayout {
                    spacing: 6px;
                    // 工作目录
                    Row {
                        Rectangle {
                            width: 90px;
                            Text {
                                text: "下载目录";
                            }
                            Text {
                                x: 74px;
                                text: "*";
                                color: red;
                            }
                        }
                        LineEdit {
                            text <=> root.work-dir;
                            read-only: true;
                            enabled: !root.is-downloading;
                        }
                        Button {
                            enabled: !root.is-downloading;
                            text: "选择";
                            clicked => { root.select-dir(); }
                        }
                    }
                    // 视频名称
                    Row {
                        Rectangle {
                            Text {
                                text: "视频名称";
                            }
                            Text {
                                x: 74px;
                                text: "*";
                                color: red;
                            }
                        }
                        LineEdit {
                            text <=> root.video-name;
                            colspan: 2;
                            enabled: !root.is-downloading;
                        }
                    }
                    // M3U8 URL
                    Row {
                        Rectangle {
                            Text {
                                text: "M3U8地址";
                            }
                            Text {
                                x: 76px;
                                text: "*";
                                color: red;
                            }
                        }
                        LineEdit {
                            text <=> root.m3u8-url;
                            colspan: 2;
                            enabled: !root.is-downloading;
                        }
                    }
                    // 线程数
                    Row {
                        Rectangle {
                            Text {
                                text: "线程数";
                            }
                        }
                        LineEdit {
                            text <=> root.threads;
                            input-type: number;
                            colspan: 2;
                            enabled: !root.is-downloading || root.is-pause;
                            placeholder-text: "4";
                        }
                    }
                    // 重试次数
                    Row {
                        Rectangle {
                            Text {
                                text: "重试次数";
                            }
                        }
                        LineEdit {
                            text <=> root.retry;
                            input-type: number;
                            colspan: 2;
                            enabled: !root.is-downloading || root.is-pause;
                            placeholder-text: "3";
                        }
                    }
                    // 超时
                    Row {
                        Rectangle {
                            Text {
                                text: "连接超时(秒)";
                            }
                        }
                        LineEdit {
                            text <=> root.timeout;
                            input-type: number;
                            colspan: 2;
                            enabled: !root.is-downloading || root.is-pause;
                            placeholder-text: "3";
                        }
                    }
                }
                // 转换MP4选项
                VerticalBox {
                    CheckBox {
                        text: "下载完成后合并为MP4";
                        checked <=> root.is-merge;
                        enabled: !root.is-downloading || root.is-pause;
                        toggled() => {
                            if !self.checked && root.is-delete-segment {
                                root.is-delete-segment = false;
                            }
                        }
                    }
                    CheckBox {
                        text: "合并后删除分片";
                        checked <=> root.is-delete-segment;
                        enabled: root.is-merge && (!root.is-downloading || root.is-pause);
                    }
                }
                // 按钮事件操作
                HorizontalBox {
                    Button {
                        text: root.is-pause ? "继续下载" : "下载";
                        enabled: root.enable-start-btn && !root.work-dir.is-empty && !root.video-name.is-empty && !root.m3u8-url.is-empty;
                        primary: true;
                        clicked => { root.start-download(); }
                    }
                    Button {
                        text: "暂停";
                        enabled: root.enable-pause-btn;
                        clicked => { root.pause-download(); }
                    }
                    Button {
                        text: "取消";
                        enabled: root.enable-cancel-btn;
                        clicked => { root.cancel-download(); }
                    }
                }
                HorizontalBox {
                    padding-bottom: 0px;
                    Text {
                        text: "下载进度 " + (root.total_nums > 0 ? root.downloaded_nums + " / " + root.total_nums : "");
                    }
                    Text {
                        text: root.total_nums > 0 ? root.content-length : "";
                    }
                }
                HorizontalBox {
                    padding-top: 0px;
                    padding-bottom: 0px;
                    Text {
                        text: root.message;
                        wrap: word-wrap;
                        color: root.is-err-msg ? #f24040 : root.normal-msg-color;
                        horizontal-alignment: center;
                    }
                }
                if root.has-failed-file : HorizontalBox {
                    padding-top: 0px;
                    padding-bottom: 0px;
                    TouchArea {
                        mouse-cursor: pointer;
                        clicked => { root.open-failed-file(); }
                        Text {
                            text: "查看下载失败的分片";
                            color: #3399ff;
                        }
                    }
                }
            }
        }
        // 关于页
        Tab {
            title: "关于";
            Rectangle {
                Text {
                    y: 140px;
                    text: "M3U8Downloader";
                }
                Text {
                    y: 160px;
                    text: "Version 0.1.0";
                }
                Text {
                    y: 180px;
                    text: "Github:";
                }
                Text {
                    y: 200px;
                    text: root.github;
                    color: #007fff;
                    TouchArea {
                        mouse-cursor: pointer;
                        clicked => {
                            Platform.open-url(root.github);
                        }
                    }
                }
            }
        }
    }
}